### ISSUE TITLE
Use a major-mode

### ISSUE THREAD

**Issue by lpw25** [let-def/sturgeon#3]
I was just playing around with the demos. One issue I had was that all the bindings are overridden by my custom bindings. This is what I expect when I use something new in emacs, and normally requires me to just write a few lines that go in the hook of the major mode. However, it seems sturgeon buffers use `fundemental` mode by default which obviously I cannot add hooks to.

So it might be good to create a major-mode for sturgeon buffers. It doesn't need to do anything, just provide builtin hooks for running code when a sturgeon app is run.

(I see the buttons are coming from `button.el`, possibly I should be trying to edit the keymaps in `button.el`, but that is always much more annoying that just editing my own keymap in a hook).

**Comment by let-def** [comment]
Done. Latest version includes a `sturgeon-mode`.
